### ISSUE TITLE
doc.internal.getLineHeight() is not a function.

### ISSUE THREAD

**Issue by MyKoi** [someatoms/jsPDF-AutoTable#33]
I am getting this error "TypeError: doc.internal.getLineHeight is not a function" when creating a PDF. I've tried just setting the line height to a number, 10 , etc.,  but the pdf does not show anything and an error message that the PDF was created incorrectly pops up.

One of the lines that uses doc.internal.getLineHeight() is line 39 in jspdf.plugin.autotable.js:
                      y += settings.lineHeight / 2 + doc.internal.getLineHeight() / 2;

Has anyone else come across this as well?
Thanks.

Stack trace:
TypeError: doc.internal.getLineHeight is not a function
    at Object.defaultOptions.renderHeaderCell (http://localhost:9081/us/r/libs/jsPDF-AutoTable-master/jspdf.plugin.autotable.js:39:61)
    at http://localhost:9081/us/r/libs/jsPDF-AutoTable-master/jspdf.plugin.autotable.js:267:22
    at Array.forEach (native)
    at printHeader (http://localhost:9081/us/r/libs/jsPDF-AutoTable-master/jspdf.plugin.autotable.js:264:17)
    at Object.API.autoTable (http://localhost:9081/us/r/libs/jsPDF-AutoTable-master/jspdf.plugin.autotable.js:89:9)
    at k.$scope.createPDF2 (http://localhost:9081/us/r/controllers.js:1937:11)
    at eb.functionCall (http://localhost:9081/us/r/libs/angular-1.3.2/angular.min.js:198:17)
    at http://localhost:9081/us/r/libs/angular-1.3.2/angular-touch.min.js:12:197
    at k.$get.k.$eval (http://localhost:9081/us/r/libs/angular-1.3.2/angular.min.js:124:250)
    at k.$get.k.$apply (http://localhost:9081/us/r/libs/angular-1.3.2/angular.min.js:124:465)

**Comment by someatoms** [comment]
Sounds strange! Do the examples work for you that is bundled in this repo? Run them by opening the `examples/examples.html`. If they do you can try basing your code on the one that best matches your app. It seems to be a configuration problem so if you are still having troubles, can you share the code you are using?

**Comment by dren79** [comment]
I have the same problem in the same place, doc.internal.getLineHeight is not a function

**Comment by dren79** [comment]
Found the solution, if we include the data.js, examples.js and jspf.debug.js files everything works perfectly.

**Comment by someatoms** [comment]
It should be enough with the `jspf.debug.js` or minified version of that file. I recommend that you use the latest file from the official jspdf library. The issue seems to be that Im using a plugin that is not always included in jspdf. I will look into this and write vetter error messages and dokumentation.

**Comment by someatoms** [comment]
All current jspdf versions (0.9, 1.0 and 1.1) are now supported in version 1.3.4 of this plugin. There should no longer be any problems with `doc.internal.getLineHeight()` or similar functions so I close this issue now.
